/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_xenaui_free(a: number): void;
export function xenaui_new(): number;
export function xenaui_parse_cir(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function xenaui_read_cir(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function xenaui_save_nodes(a: number, b: number, c: number, d: number): void;
export function xenaui_set_source(a: number, b: number, c: number, d: number, e: number): void;
export function xenaui_set_tr_time(a: number, b: number, c: number): void;
export function xenaui_solve(a: number, b: number): void;
export function xenaui_step(a: number, b: number, c: number): void;
export function xenaui_set_val(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function xenaui_sweep(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function xenaui_add_device(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function xenaui_add_model(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function xenaui_add_geometry(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function xenaui_width(a: number): number;
export function xenaui_height(a: number): number;
export function xenaui_render(a: number, b: number): void;
export function __wbgt_run_rendering_0(a: number): void;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5936b393a5590405(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h50e4f9626559145c(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h44b872ba63f20078(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h14165df31733bf64(a: number, b: number, c: number, d: number): void;
